from __future__ import annotations

import json
import re
from typing import Any

from .schema_types import SourceError, TargetLangSpec
from .validate import inferred_equality_mode, require_list


NIM_SCALAR_BACKINGS = {
    "string": "bskString",
    "f32": "bskF32",
    "f64": "bskF64",
    "bool": "bskBool",
    "varint": "bskVarint",
    "varuint": "bskVaruint",
}

def emit_runtime_metadata(registry: dict[str, Any], defaults: dict[str, Any], spec: TargetLangSpec) -> str:
    backing_types = require_list(registry, "backingTypes")
    type_keys = require_list(registry, "typeKeys")
    property_keys = require_list(registry, "propertyKeys")
    objects = require_list(registry, "objects")
    ordinal_enums = require_list(registry, "ordinalEnums")
    object_defaults = require_list(defaults, "objectDefaults")
    required_properties = require_list(defaults, "requiredProperties")
    lines = [
        f"{spec.comment_prefix} Generated by codegen/generate.py; do not edit by hand.",
        "",
    ]
    lines.extend(spec.declarations)
    lines.extend([spec.registry_version_line(registry["registryVersion"]), spec.backing_types_start])
    for entry in backing_types:
        lines.append(spec.backing_type_record(entry))
    lines.extend([spec.backing_types_end, *spec.type_key_prefix_lines(type_keys), spec.type_keys_start])
    for entry in type_keys:
        lines.append(spec.type_key_record(entry))
    lines.extend([spec.type_keys_end, *spec.property_key_prefix_lines(property_keys), spec.property_keys_start])
    for entry in property_keys:
        lines.append(spec.property_key_record(entry))
    lines.extend([spec.property_keys_end, spec.object_specs_start])
    for entry in objects:
        properties = spec.object_properties_literal(entry["properties"])
        lines.append(spec.object_spec_record(entry, properties))
    lines.extend([spec.object_specs_end, spec.property_defaults_start])
    for entry in object_defaults:
        object_id = entry["object"]
        for property_id, default in entry.get("properties", {}).items():
            equality = default.get("equality") or inferred_equality_mode(
                property_backing_type(registry, property_id)
            )
            lines.append(
                spec.property_default_record(
                    object_id,
                    property_id,
                    equality,
                    spec.json_text_literal(default["value"]),
                    spec.bool_literal(default["omitWhenDefault"]),
                    spec.bool_literal(default["applyOnLoad"]),
                )
            )
    lines.extend([spec.property_defaults_end, spec.required_properties_start])
    for entry in required_properties:
        lines.append(spec.required_property_record(entry, spec.string_literal(entry["reason"])))
    lines.extend([spec.required_properties_end, spec.ordinal_enums_start])
    for entry in ordinal_enums:
        values = spec.object_properties_literal(entry["values"])
        lines.append(spec.ordinal_enum_record(entry, values))
    lines.extend([spec.ordinal_enums_end, *spec.trailer])
    return "\n".join(lines)


def nim_identifier_suffix(identifier: str) -> str:
    return dart_const_suffix(identifier)


def nim_scalar_value_literal(backing_type: str, value: Any | None) -> str:
    if backing_type == "string":
        return f"bonyStringValue({nim_string_literal(value if isinstance(value, str) else '')})"
    if backing_type == "f32":
        numeric = 0.0 if value is None else value
        return f"bonyF32Value({float(numeric)!r})"
    if backing_type == "f64":
        numeric = 0.0 if value is None else value
        return f"bonyF64Value({float(numeric)!r})"
    if backing_type == "bool":
        return f"bonyBoolValue({generated_bool(bool(value))})"
    if backing_type == "varint":
        numeric = 0 if value is None else int(value)
        return f"bonyIntValue({numeric}.int64)"
    if backing_type == "varuint":
        numeric = 0 if value is None else int(value)
        return f"bonyUintValue({numeric}.uint64)"
    raise SourceError(f"unsupported Nim scalar backing type {backing_type}")


def nim_scalar_codec_lines(registry: dict[str, Any], defaults: dict[str, Any]) -> list[str]:
    type_keys = require_list(registry, "typeKeys")
    property_keys = require_list(registry, "propertyKeys")
    objects = require_list(registry, "objects")
    property_by_id = {entry["id"]: entry for entry in property_keys}
    type_key_by_id = {entry["id"]: entry["key"] for entry in type_keys}
    default_map = {
        entry["object"]: entry.get("properties", {})
        for entry in require_list(defaults, "objectDefaults")
    }
    required_map: dict[str, set[str]] = {}
    for entry in require_list(defaults, "requiredProperties"):
        required_map.setdefault(entry["object"], set()).add(entry["property"])

    lines = [
        "",
        "type",
        "  BonyScalarKind* = enum",
        "    bskString, bskF32, bskF64, bskBool, bskVarint, bskVaruint",
        "  BonyScalarValue* = object",
        "    case kind*: BonyScalarKind",
        "    of bskString:",
        "      stringValue*: string",
        "    of bskF32, bskF64:",
        "      floatValue*: float64",
        "    of bskBool:",
        "      boolValue*: bool",
        "    of bskVarint:",
        "      intValue*: int64",
        "    of bskVaruint:",
        "      uintValue*: uint64",
        "  BonyJsonScalarProperty* = object",
        "    propertyId*: string",
        "    value*: BonyScalarValue",
        "  BonyBnbScalarProperty* = object",
        "    propertyKey*: uint64",
        "    value*: BonyScalarValue",
        "  BonyScalarPropertySpec* = object",
        "    objectId*: string",
        "    propertyId*: string",
        "    propertyKey*: uint64",
        "    kind*: BonyScalarKind",
        "    required*: bool",
        "    hasDefault*: bool",
        "    defaultValue*: BonyScalarValue",
        "    equality*: string",
        "    omitWhenDefault*: bool",
        "    applyOnLoad*: bool",
        "",
        "func bonyStringValue*(value: string): BonyScalarValue =",
        "  BonyScalarValue(kind: bskString, stringValue: value)",
        "",
        "func bonyF32Value*(value: float64): BonyScalarValue =",
        "  BonyScalarValue(kind: bskF32, floatValue: value)",
        "",
        "func bonyF64Value*(value: float64): BonyScalarValue =",
        "  BonyScalarValue(kind: bskF64, floatValue: value)",
        "",
        "func bonyBoolValue*(value: bool): BonyScalarValue =",
        "  BonyScalarValue(kind: bskBool, boolValue: value)",
        "",
        "func bonyIntValue*(value: int64): BonyScalarValue =",
        "  BonyScalarValue(kind: bskVarint, intValue: value)",
        "",
        "func bonyUintValue*(value: uint64): BonyScalarValue =",
        "  BonyScalarValue(kind: bskVaruint, uintValue: value)",
        "",
        "proc bonyScalarMatchesKind(value: BonyScalarValue; kind: BonyScalarKind): bool =",
        "  if kind == bskF32:",
        "    return value.kind in {bskF32, bskF64}",
        "  value.kind == kind",
        "",
        "proc bonyScalarEquals(value, defaultValue: BonyScalarValue; equality: string): bool =",
        "  if equality == \"storedF32\":",
        "    return value.kind in {bskF32, bskF64} and defaultValue.kind in {bskF32, bskF64} and",
        "      float32(value.floatValue) == float32(defaultValue.floatValue)",
        "  if not value.bonyScalarMatchesKind(defaultValue.kind):",
        "    return false",
        "  case defaultValue.kind",
        "  of bskString:",
        "    value.stringValue == defaultValue.stringValue",
        "  of bskF32:",
        "    value.floatValue == defaultValue.floatValue",
        "  of bskF64:",
        "    value.floatValue == defaultValue.floatValue",
        "  of bskBool:",
        "    value.boolValue == defaultValue.boolValue",
        "  of bskVarint:",
        "    value.intValue == defaultValue.intValue",
        "  of bskVaruint:",
        "    value.uintValue == defaultValue.uintValue",
        "",
        "proc bonyFindJsonScalar(properties: openArray[BonyJsonScalarProperty]; propertyId: string): int =",
        "  for index, property in properties:",
        "    if property.propertyId == propertyId:",
        "      return index",
        "  -1",
        "",
        "proc bonyFindBnbScalar(properties: openArray[BonyBnbScalarProperty]; propertyKey: uint64): int =",
        "  for index, property in properties:",
        "    if property.propertyKey == propertyKey:",
        "      return index",
        "  -1",
        "",
        "proc bonyValidateJsonScalar(specs: openArray[BonyScalarPropertySpec]; property: BonyJsonScalarProperty) =",
        "  for spec in specs:",
        "    if spec.propertyId == property.propertyId:",
        "      if not property.value.bonyScalarMatchesKind(spec.kind):",
        "        raise newException(ValueError, \"wrong scalar kind for \" & spec.objectId & \".\" & spec.propertyId)",
        "      return",
        "  raise newException(ValueError, \"unknown scalar property id: \" & property.propertyId)",
        "",
        "proc bonyValidateBnbScalar(specs: openArray[BonyScalarPropertySpec]; property: BonyBnbScalarProperty) =",
        "  for spec in specs:",
        "    if spec.propertyKey == property.propertyKey:",
        "      if not property.value.bonyScalarMatchesKind(spec.kind):",
        "        raise newException(ValueError, \"wrong scalar kind for \" & spec.objectId & \".\" & spec.propertyId)",
        "      return",
        "  raise newException(ValueError, \"unknown scalar property key: \" & $property.propertyKey)",
        "",
        "proc bonyValidateJsonScalarProperties(specs: openArray[BonyScalarPropertySpec]; properties: openArray[BonyJsonScalarProperty]) =",
        "  var seen: seq[string]",
        "  for property in properties:",
        "    if property.propertyId in seen:",
        "      raise newException(ValueError, \"duplicate scalar property id: \" & property.propertyId)",
        "    seen.add property.propertyId",
        "    bonyValidateJsonScalar(specs, property)",
        "",
        "proc bonyValidateBnbScalarProperties(specs: openArray[BonyScalarPropertySpec]; properties: openArray[BonyBnbScalarProperty]) =",
        "  var seen: seq[uint64]",
        "  for property in properties:",
        "    if property.propertyKey in seen:",
        "      raise newException(ValueError, \"duplicate scalar property key: \" & $property.propertyKey)",
        "    seen.add property.propertyKey",
        "    bonyValidateBnbScalar(specs, property)",
        "",
        "proc bonyEncodeJsonScalars*(specs: openArray[BonyScalarPropertySpec]; properties: openArray[BonyJsonScalarProperty]): seq[BonyJsonScalarProperty] =",
        "  bonyValidateJsonScalarProperties(specs, properties)",
        "  for spec in specs:",
        "    let index = properties.bonyFindJsonScalar(spec.propertyId)",
        "    if index < 0:",
        "      if spec.required:",
        "        raise newException(ValueError, \"missing required scalar property: \" & spec.objectId & \".\" & spec.propertyId)",
        "      continue",
        "    let value = properties[index].value",
        "    if spec.omitWhenDefault and spec.hasDefault and bonyScalarEquals(value, spec.defaultValue, spec.equality):",
        "      continue",
        "    result.add BonyJsonScalarProperty(propertyId: spec.propertyId, value: value)",
        "",
        "proc bonyDecodeJsonScalars*(specs: openArray[BonyScalarPropertySpec]; properties: openArray[BonyJsonScalarProperty]): seq[BonyJsonScalarProperty] =",
        "  bonyValidateJsonScalarProperties(specs, properties)",
        "  for spec in specs:",
        "    let index = properties.bonyFindJsonScalar(spec.propertyId)",
        "    if index >= 0:",
        "      result.add BonyJsonScalarProperty(propertyId: spec.propertyId, value: properties[index].value)",
        "    elif spec.hasDefault and spec.applyOnLoad:",
        "      result.add BonyJsonScalarProperty(propertyId: spec.propertyId, value: spec.defaultValue)",
        "    elif spec.required:",
        "      raise newException(ValueError, \"missing required scalar property: \" & spec.objectId & \".\" & spec.propertyId)",
        "",
        "proc bonyEncodeBnbScalars*(specs: openArray[BonyScalarPropertySpec]; properties: openArray[BonyBnbScalarProperty]): seq[BonyBnbScalarProperty] =",
        "  bonyValidateBnbScalarProperties(specs, properties)",
        "  for spec in specs:",
        "    let index = properties.bonyFindBnbScalar(spec.propertyKey)",
        "    if index < 0:",
        "      if spec.required:",
        "        raise newException(ValueError, \"missing required scalar property: \" & spec.objectId & \".\" & spec.propertyId)",
        "      continue",
        "    let value = properties[index].value",
        "    if spec.omitWhenDefault and spec.hasDefault and bonyScalarEquals(value, spec.defaultValue, spec.equality):",
        "      continue",
        "    result.add BonyBnbScalarProperty(propertyKey: spec.propertyKey, value: value)",
        "",
        "proc bonyDecodeBnbScalars*(specs: openArray[BonyScalarPropertySpec]; properties: openArray[BonyBnbScalarProperty]): seq[BonyBnbScalarProperty] =",
        "  bonyValidateBnbScalarProperties(specs, properties)",
        "  for spec in specs:",
        "    let index = properties.bonyFindBnbScalar(spec.propertyKey)",
        "    if index >= 0:",
        "      result.add BonyBnbScalarProperty(propertyKey: spec.propertyKey, value: properties[index].value)",
        "    elif spec.hasDefault and spec.applyOnLoad:",
        "      result.add BonyBnbScalarProperty(propertyKey: spec.propertyKey, value: spec.defaultValue)",
        "    elif spec.required:",
        "      raise newException(ValueError, \"missing required scalar property: \" & spec.objectId & \".\" & spec.propertyId)",
        "",
    ]

    scalar_object_ids: list[str] = []
    for obj in objects:
        object_id = obj["type"]
        scalar_properties = [
            property_id
            for property_id in obj["properties"]
            if property_by_id[property_id]["backingType"] in NIM_SCALAR_BACKINGS
        ]
        scalar_object_ids.append(object_id)
        suffix = nim_identifier_suffix(object_id)
        if scalar_properties:
            lines.append(f"const bony{suffix}ScalarSpecs* = [")
            for property_id in scalar_properties:
                property_entry = property_by_id[property_id]
                backing_type = property_entry["backingType"]
                default = default_map.get(object_id, {}).get(property_id)
                equality = (default or {}).get("equality") or inferred_equality_mode(backing_type)
                default_value = default["value"] if default is not None else None
                lines.append(
                    "  BonyScalarPropertySpec("
                    f"objectId: {nim_string_literal(object_id)}, "
                    f"propertyId: {nim_string_literal(property_id)}, "
                    f"propertyKey: {property_entry['key']}.uint64, "
                    f"kind: {NIM_SCALAR_BACKINGS[backing_type]}, "
                    f"required: {generated_bool(property_id in required_map.get(object_id, set()))}, "
                    f"hasDefault: {generated_bool(default is not None)}, "
                    f"defaultValue: {nim_scalar_value_literal(backing_type, default_value)}, "
                    f"equality: {nim_string_literal(equality)}, "
                    f"omitWhenDefault: {generated_bool(default['omitWhenDefault'] if default is not None else False)}, "
                    f"applyOnLoad: {generated_bool(default['applyOnLoad'] if default is not None else False)}),"
                )
        else:
            lines.append(f"const bony{suffix}ScalarSpecs*: array[0, BonyScalarPropertySpec] = []")
        if scalar_properties:
            lines.append("]")
        lines.extend(
            [
                "",
                f"proc encode{suffix}JsonScalars*(properties: openArray[BonyJsonScalarProperty]): seq[BonyJsonScalarProperty] =",
                f"  bonyEncodeJsonScalars(bony{suffix}ScalarSpecs, properties)",
                "",
                f"proc decode{suffix}JsonScalars*(properties: openArray[BonyJsonScalarProperty]): seq[BonyJsonScalarProperty] =",
                f"  bonyDecodeJsonScalars(bony{suffix}ScalarSpecs, properties)",
                "",
                f"proc encode{suffix}BnbScalars*(properties: openArray[BonyBnbScalarProperty]): seq[BonyBnbScalarProperty] =",
                f"  bonyEncodeBnbScalars(bony{suffix}ScalarSpecs, properties)",
                "",
                f"proc decode{suffix}BnbScalars*(properties: openArray[BonyBnbScalarProperty]): seq[BonyBnbScalarProperty] =",
                f"  bonyDecodeBnbScalars(bony{suffix}ScalarSpecs, properties)",
                "",
            ]
        )

    lines.extend(
        [
            "proc encodeBonyObjectJsonScalars*(typeId: string; properties: openArray[BonyJsonScalarProperty]): seq[BonyJsonScalarProperty] =",
            "  discard bonyObjectSpec(typeId)",
            "  case typeId",
        ]
    )
    for object_id in scalar_object_ids:
        suffix = nim_identifier_suffix(object_id)
        lines.append(f"  of {nim_string_literal(object_id)}: encode{suffix}JsonScalars(properties)")
    lines.extend(
        [
            "  else: @[]",
            "",
            "proc decodeBonyObjectJsonScalars*(typeId: string; properties: openArray[BonyJsonScalarProperty]): seq[BonyJsonScalarProperty] =",
            "  discard bonyObjectSpec(typeId)",
            "  case typeId",
        ]
    )
    for object_id in scalar_object_ids:
        suffix = nim_identifier_suffix(object_id)
        lines.append(f"  of {nim_string_literal(object_id)}: decode{suffix}JsonScalars(properties)")
    lines.extend(
        [
            "  else: @[]",
            "",
            "proc encodeBonyObjectBnbScalars*(typeKey: uint64; properties: openArray[BonyBnbScalarProperty]): seq[BonyBnbScalarProperty] =",
            "  case typeKey",
        ]
    )
    for object_id in scalar_object_ids:
        suffix = nim_identifier_suffix(object_id)
        lines.append(f"  of {type_key_by_id[object_id]}.uint64: encode{suffix}BnbScalars(properties)")
    lines.extend(
        [
            "  else:",
            "    for item in bonyTypeKeys:",
            "      if item.key == typeKey:",
            "        return @[]",
            "    raise newException(ValueError, \"unknown bony object type key: \" & $typeKey)",
            "",
            "proc decodeBonyObjectBnbScalars*(typeKey: uint64; properties: openArray[BonyBnbScalarProperty]): seq[BonyBnbScalarProperty] =",
            "  case typeKey",
        ]
    )
    for object_id in scalar_object_ids:
        suffix = nim_identifier_suffix(object_id)
        lines.append(f"  of {type_key_by_id[object_id]}.uint64: decode{suffix}BnbScalars(properties)")
    lines.extend(
        [
            "  else:",
            "    for item in bonyTypeKeys:",
            "      if item.key == typeKey:",
            "        return @[]",
            "    raise newException(ValueError, \"unknown bony object type key: \" & $typeKey)",
            "",
        ]
    )
    return lines


def generate_nim(registry: dict[str, Any], defaults: dict[str, Any]) -> str:
    spec = TargetLangSpec(
        comment_prefix="##",
        declarations=(
            "type",
            "  BonyBackingType* = object",
            "    id*: string",
            "    code*: uint8",
            "  BonyTypeKey* = object",
            "    id*: string",
            "    key*: uint64",
            "  BonyPropertyKey* = object",
            "    id*: string",
            "    key*: uint64",
            "    backingType*: string",
            "  BonyObjectSpec* = object",
            "    typeId*: string",
            "    properties*: seq[string]",
            "  BonyPropertyDefault* = object",
            "    objectId*: string",
            "    propertyId*: string",
            "    equality*: string",
            "    value*: string",
            "    omitWhenDefault*: bool",
            "    applyOnLoad*: bool",
            "  BonyRequiredProperty* = object",
            "    objectId*: string",
            "    propertyId*: string",
            "    reason*: string",
            "  BonyOrdinalEnum* = object",
            "    id*: string",
            "    values*: seq[string]",
            "",
        ),
        registry_version_line=lambda version: f"const bonyRegistryVersion* = {version}",
        backing_types_start="const bonyBackingTypes* = [",
        backing_types_end="]",
        type_key_prefix_lines=lambda _entries: [],
        type_keys_start="const bonyTypeKeys* = [",
        type_keys_end="]",
        property_key_prefix_lines=lambda _entries: [],
        property_keys_start="const bonyPropertyKeys* = [",
        property_keys_end="]",
        object_specs_start="let bonyObjectSpecs*: seq[BonyObjectSpec] = @[",
        object_specs_end="]",
        property_defaults_start="const bonyPropertyDefaults* = [",
        property_defaults_end="]",
        required_properties_start="const bonyRequiredProperties* = [",
        required_properties_end="]",
        ordinal_enums_start="let bonyOrdinalEnums*: seq[BonyOrdinalEnum] = @[",
        ordinal_enums_end="]",
        object_properties_literal=lambda properties: "@["
        + ", ".join(nim_string_literal(property_id) for property_id in properties)
        + "]",
        json_text_literal=lambda value: nim_string_literal(canonical_json_value(value)),
        string_literal=nim_string_literal,
        bool_literal=generated_bool,
        backing_type_record=lambda entry: (
            f"  BonyBackingType(id: {nim_string_literal(entry['id'])}, code: {entry['code']}.uint8),"
        ),
        type_key_record=lambda entry: (
            f"  BonyTypeKey(id: {nim_string_literal(entry['id'])}, key: {entry['key']}.uint64),"
        ),
        property_key_record=lambda entry: (
            f"  BonyPropertyKey(id: {nim_string_literal(entry['id'])}, key: {entry['key']}.uint64, "
            f"backingType: {nim_string_literal(entry['backingType'])}),"
        ),
        object_spec_record=lambda entry, properties: (
            f"  BonyObjectSpec(typeId: {nim_string_literal(entry['type'])}, properties: {properties}),"
        ),
        property_default_record=lambda object_id, property_id, equality, value, omit, apply: (
            f"  BonyPropertyDefault(objectId: {nim_string_literal(object_id)}, "
            f"propertyId: {nim_string_literal(property_id)}, "
            f"equality: {nim_string_literal(equality)}, "
            f"value: {value}, "
            f"omitWhenDefault: {omit}, "
            f"applyOnLoad: {apply}),"
        ),
        required_property_record=lambda entry, reason: (
            f"  BonyRequiredProperty(objectId: {nim_string_literal(entry['object'])}, "
            f"propertyId: {nim_string_literal(entry['property'])}, reason: {reason}),"
        ),
        ordinal_enum_record=lambda entry, values: (
            f"  BonyOrdinalEnum(id: {nim_string_literal(entry['id'])}, values: {values}),"
        ),
        trailer=(
            "",
            "proc bonyObjectSpec*(typeId: string): BonyObjectSpec =",
            "  for spec in bonyObjectSpecs:",
            "    if spec.typeId == typeId:",
            "      return spec",
            "  raise newException(ValueError, \"unknown bony object type: \" & typeId)",
            *nim_scalar_codec_lines(registry, defaults),
            "proc encodeBonyObject*(typeId: string) =",
            "  discard bonyObjectSpec(typeId)",
            "  raise newException(CatchableError, \"generated encodeBonyObject has no registered fields yet\")",
            "",
            "proc decodeBonyObject*(typeId: string) =",
            "  discard bonyObjectSpec(typeId)",
            "  raise newException(CatchableError, \"generated decodeBonyObject has no registered fields yet\")",
            "",
        ),
    )
    return emit_runtime_metadata(registry, defaults, spec)


def generate_dart(registry: dict[str, Any], defaults: dict[str, Any]) -> str:
    type_keys = require_list(registry, "typeKeys")
    property_keys = require_list(registry, "propertyKeys")
    type_const_names = dart_const_names(type_keys, "bonyTypeKey", "type key")
    property_const_names = dart_const_names(property_keys, "bonyPropertyKey", "property key")
    spec = TargetLangSpec(
        comment_prefix="//",
        declarations=(
            "class BonyBackingType {",
            "  const BonyBackingType({required this.id, required this.code});",
            "  final String id;",
            "  final int code;",
            "}",
            "",
            "class BonyTypeKey {",
            "  const BonyTypeKey({required this.id, required this.key});",
            "  final String id;",
            "  final int key;",
            "}",
            "",
            "class BonyPropertyKey {",
            "  const BonyPropertyKey({",
            "    required this.id,",
            "    required this.key,",
            "    required this.backingType,",
            "  });",
            "  final String id;",
            "  final int key;",
            "  final String backingType;",
            "}",
            "",
            "class BonyObjectSpec {",
            "  const BonyObjectSpec({required this.typeId, required this.properties});",
            "  final String typeId;",
            "  final List<String> properties;",
            "}",
            "",
            "class BonyPropertyDefault {",
            "  const BonyPropertyDefault({",
            "    required this.objectId,",
            "    required this.propertyId,",
            "    required this.equality,",
            "    required this.value,",
            "    required this.omitWhenDefault,",
            "    required this.applyOnLoad,",
            "  });",
            "  final String objectId;",
            "  final String propertyId;",
            "  final String equality;",
            "  final String value;",
            "  final bool omitWhenDefault;",
            "  final bool applyOnLoad;",
            "}",
            "",
            "class BonyRequiredProperty {",
            "  const BonyRequiredProperty({",
            "    required this.objectId,",
            "    required this.propertyId,",
            "    required this.reason,",
            "  });",
            "  final String objectId;",
            "  final String propertyId;",
            "  final String reason;",
            "}",
            "",
            "class BonyOrdinalEnum {",
            "  const BonyOrdinalEnum({required this.id, required this.values});",
            "  final String id;",
            "  final List<String> values;",
            "}",
            "",
        ),
        registry_version_line=lambda version: f"const int bonyRegistryVersion = {version};",
        backing_types_start="const List<BonyBackingType> bonyBackingTypes = [",
        backing_types_end="];",
        type_key_prefix_lines=lambda entries: [
            "",
            "// Registry-derived type keys for compile-time loader use.",
            *[f"const int {type_const_names[entry['id']]} = {entry['key']};" for entry in entries],
            "",
        ],
        type_keys_start="const List<BonyTypeKey> bonyTypeKeys = [",
        type_keys_end="];",
        property_key_prefix_lines=lambda entries: [
            "",
            "// Registry-derived property keys for compile-time loader use.",
            *[f"const int {property_const_names[entry['id']]} = {entry['key']};" for entry in entries],
            "",
        ],
        property_keys_start="const List<BonyPropertyKey> bonyPropertyKeys = [",
        property_keys_end="];",
        object_specs_start="const List<BonyObjectSpec> bonyObjectSpecs = [",
        object_specs_end="];",
        property_defaults_start="const List<BonyPropertyDefault> bonyPropertyDefaults = [",
        property_defaults_end="];",
        required_properties_start="const List<BonyRequiredProperty> bonyRequiredProperties = [",
        required_properties_end="];",
        ordinal_enums_start="const List<BonyOrdinalEnum> bonyOrdinalEnums = [",
        ordinal_enums_end="];",
        object_properties_literal=lambda properties: "["
        + ", ".join(dart_string_literal(property_id) for property_id in properties)
        + "]",
        json_text_literal=lambda value: dart_string_literal(canonical_json_value(value)),
        string_literal=dart_string_literal,
        bool_literal=generated_bool,
        backing_type_record=lambda entry: (
            f"  BonyBackingType(id: {dart_registry_string_literal(entry['id'])}, code: {entry['code']}),"
        ),
        type_key_record=lambda entry: (
            f"  BonyTypeKey(id: {dart_registry_string_literal(entry['id'])}, key: {type_const_names[entry['id']]}),"
        ),
        property_key_record=lambda entry: (
            f"  BonyPropertyKey(id: {dart_registry_string_literal(entry['id'])}, "
            f"key: {property_const_names[entry['id']]}, "
            f"backingType: {dart_registry_string_literal(entry['backingType'])}),"
        ),
        object_spec_record=lambda entry, properties: (
            f"  BonyObjectSpec(typeId: {dart_registry_string_literal(entry['type'])}, properties: {properties}),"
        ),
        property_default_record=lambda object_id, property_id, equality, value, omit, apply: (
            f"  BonyPropertyDefault(objectId: {dart_registry_string_literal(object_id)}, "
            f"propertyId: {dart_registry_string_literal(property_id)}, "
            f"equality: {dart_registry_string_literal(equality)}, "
            f"value: {value}, "
            f"omitWhenDefault: {omit}, "
            f"applyOnLoad: {apply}),"
        ),
        required_property_record=lambda entry, reason: (
            f"  BonyRequiredProperty(objectId: {dart_registry_string_literal(entry['object'])}, "
            f"propertyId: {dart_registry_string_literal(entry['property'])}, reason: {reason}),"
        ),
        ordinal_enum_record=lambda entry, values: (
            f"  BonyOrdinalEnum(id: {dart_registry_string_literal(entry['id'])}, values: {values}),"
        ),
        trailer=(
            "",
            "BonyObjectSpec bonyObjectSpec(String typeId) {",
            "  return bonyObjectSpecs.firstWhere(",
            "    (spec) => spec.typeId == typeId,",
            "    orElse: () => throw ArgumentError.value(typeId, 'typeId', 'unknown bony object type'),",
            "  );",
            "}",
            "",
            "Never encodeBonyObject(String typeId) {",
            "  bonyObjectSpec(typeId);",
            "  throw UnsupportedError('generated encodeBonyObject has no registered fields yet');",
            "}",
            "",
            "Never decodeBonyObject(String typeId) {",
            "  bonyObjectSpec(typeId);",
            "  throw UnsupportedError('generated decodeBonyObject has no registered fields yet');",
            "}",
            "",
        ),
    )
    return emit_runtime_metadata(registry, defaults, spec)


def property_backing_type(registry: dict[str, Any], property_id: str) -> str:
    for entry in require_list(registry, "propertyKeys"):
        if entry["id"] == property_id:
            return entry["backingType"]
    raise SourceError(f"unknown property id {property_id}")


def canonical_json_value(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def nim_json_text(value: Any) -> str:
    return escape_string(json.dumps(value, sort_keys=True, separators=(",", ":")))


def escape_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")


def nim_string_literal(value: str) -> str:
    return '"' + escape_string(value) + '"'


def dart_string_literal(value: str) -> str:
    return json.dumps(value).replace("$", r"\$")


def dart_registry_string_literal(value: str) -> str:
    return "'" + escape_string(value) + "'"


def dart_const_suffix(identifier: str) -> str:
    if not identifier:
        raise SourceError("Dart const identifier suffix must not be empty")
    suffix = identifier[0].upper() + identifier[1:]
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", suffix):
        raise SourceError(f"registry id {identifier!r} cannot form a Dart const suffix")
    return suffix


def dart_const_names(entries: list[dict[str, Any]], prefix: str, label: str) -> dict[str, str]:
    result: dict[str, str] = {}
    seen: dict[str, str] = {}
    for entry in entries:
        identifier = entry.get("id")
        if not isinstance(identifier, str) or not identifier:
            raise SourceError(f"{label} id must be a non-empty string")
        name = prefix + dart_const_suffix(identifier)
        previous = seen.get(name)
        if previous is not None:
            raise SourceError(
                f"duplicate generated Dart const name {name!r} for {label} ids "
                f"{previous!r} and {identifier!r}"
            )
        seen[name] = identifier
        result[identifier] = name
    return result


def generated_bool(value: bool) -> str:
    return "true" if value else "false"
