// Dart M13 numeric gate: mesh attachment x deformer draw-batch semantics.
//
// This pins the mesh-x-deformer contract (bony-5pwj): a skinned mesh draw
// batch IS further deformed by warp/rotation deformers, exactly like a region
// batch. Dart's buildDrawBatches runs every base batch (region AND mesh)
// through applyDeformers after skinning; the Nim CLI golden pipeline
// (applyDeformersToDrawBatches) does the same. Both are vertex-count-agnostic,
// so this rig uses a 5-vertex mesh (NOT the 4-vertex region-quad count) to
// prove applyDeformers handles arbitrary mesh vertex counts without crashing.
//
// Loads m13_mesh_deform_rig.bony, builds draw batches (applies the rotation
// deformer at default parameters), and compares vertex positions against the
// committed golden (conformance/goldens/m13_mesh_deform_rig_t0.json) within
// tolerance (abs <= 1e-4). The golden is generated by the Nim CLI, so a match
// proves Nim and Dart agree on mesh-x-deformer output.
//
// Tests run from runtime-dart/ so ../conformance/ resolves to repo root.

import 'dart:convert';
import 'dart:io';
import 'package:test/test.dart';
import 'package:bony/bony.dart';

const double _tol = 1e-4;

void _expectClose(double actual, double expected, String label) {
  expect(
    (actual - expected).abs(),
    lessThanOrEqualTo(_tol),
    reason: '$label: actual=$actual expected=$expected diff=${(actual - expected).abs()}',
  );
}

void main() {
  late SkeletonData data;
  late List<DrawBatch> batches;
  late Map<String, dynamic> golden;

  setUpAll(() {
    data = loadBonyJson(
      File('../conformance/assets/m13_mesh_deform_rig.bony').readAsStringSync(),
    );
    batches = buildDrawBatches(data);
    golden = jsonDecode(
      File('../conformance/goldens/m13_mesh_deform_rig_t0.json').readAsStringSync(),
    ) as Map<String, dynamic>;
  });

  group('M13 rig loads a mesh and a deformer together', () {
    test('one mesh attachment present', () {
      expect(data.meshAttachments, hasLength(1));
      expect(data.meshAttachments.single.weighted, isTrue);
    });

    test('one rotation deformer present', () {
      expect(data.deformers, hasLength(1));
      final rec = data.deformers.single;
      expect(rec.deformer.id, 'mesh_rot');
      expect(rec.deformer.kind, DeformerKind.rotation);
    });
  });

  group('M13 draw batches vs golden (abs <= 1e-4)', () {
    test('single mesh batch with a non-quad vertex count', () {
      expect(batches, hasLength(1));
      // 5 vertices, deliberately != 4, so applyDeformers is exercised on an
      // arbitrary mesh vertex count rather than a region quad.
      expect(batches.single.vertices, hasLength(5));
      expect(batches.single.slot, 'mesh_slot');
    });

    test('batch count matches golden', () {
      final goldenBatches = (golden['drawBatches'] as List<dynamic>)
          .cast<Map<String, dynamic>>();
      expect(batches, hasLength(goldenBatches.length));
    });

    test('all batch vertices match golden (deformer applied to mesh)', () {
      final goldenBatches = (golden['drawBatches'] as List<dynamic>)
          .cast<Map<String, dynamic>>();

      for (var bi = 0; bi < goldenBatches.length; bi++) {
        final gb = goldenBatches[bi];
        final batch = batches[bi];
        final slotName = gb['slot'] as String;

        expect(batch.slot, slotName, reason: 'batch[$bi] slot mismatch');

        final goldenVerts =
            (gb['vertices'] as List<dynamic>).cast<Map<String, dynamic>>();
        expect(batch.vertices, hasLength(goldenVerts.length),
            reason: '$slotName vertex count mismatch');

        // Indices survive the deformer re-map unchanged.
        final goldenIndices =
            (gb['indices'] as List<dynamic>).map((e) => e as int).toList();
        expect(batch.indices, goldenIndices,
            reason: '$slotName indices mismatch');

        for (var vi = 0; vi < goldenVerts.length; vi++) {
          final gv = goldenVerts[vi];
          final v = batch.vertices[vi];
          final prefix = '$slotName[v$vi]';
          _expectClose(v.x, (gv['x'] as num).toDouble(), '$prefix.x');
          _expectClose(v.y, (gv['y'] as num).toDouble(), '$prefix.y');
          _expectClose(v.u, (gv['u'] as num).toDouble(), '$prefix.u');
          _expectClose(v.v, (gv['v'] as num).toDouble(), '$prefix.v');
        }
      }
    });

    test('deformer actually moved the mesh (non-vacuous)', () {
      // Undeformed, the first mesh vertex skins to world (5,5) — the rotation
      // pivot — so it must stay put, while vertex 1 skins to (14,0) and must
      // move. If Dart ever stopped deforming mesh batches, v1 would read (14,0)
      // and this (plus the golden comparison) would fail.
      final verts = batches.single.vertices;
      _expectClose(verts[0].x, 5.0, 'v0.x (at pivot)');
      _expectClose(verts[0].y, 5.0, 'v0.y (at pivot)');
      expect((verts[1].x - 14.0).abs() > 0.5 || (verts[1].y - 0.0).abs() > 0.5,
          isTrue,
          reason: 'v1 should have been rotated away from its (14,0) skinned position');
    });
  });
}
